export const navStyles = {
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 5%",
    height: 64,
    background: "rgba(10,10,15,0.92)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #1a1a2e",
  },
  navLogo: {
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 22,
    color: "#00f5c4",
    letterSpacing: 2,
  },
  navLinks: {
    display: "flex",
    gap: 8,
  },
  navLink: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "#aaa",
    cursor: "pointer",
    fontSize: 14,
    padding: "4px 12px",
    transition: "color 0.2s",
    fontFamily: "'DM Sans', sans-serif",
  },
  menuBtn: {
    display: "none",
    background: "none",
    border: "none",
    color: "#00f5c4",
    fontSize: 22,
    cursor: "pointer",
  },
  mobileMenu: {
    position: "fixed",
    top: 64,
    left: 0,
    right: 0,
    zIndex: 99,
    background: "#0d0d18",
    borderBottom: "1px solid #1a1a2e",
    display: "flex",
    flexDirection: "column",
    padding: "8px 0",
  },
  mobileMenuLink: {
    background: "none",
    border: "none",
    color: "#ccc",
    padding: "12px 5%",
    textAlign: "left",
    fontSize: 15,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
};

export const heroStyles = {
  hero: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "100px 6% 60px",
    position: "relative",
    zIndex: 1,
    flexWrap: "wrap",
    gap: 40,
  },
  heroContent: { flex: "1 1 340px", maxWidth: 560 },
  heroGreet: { fontSize: 18, color: "#00f5c4", marginBottom: 8, fontFamily: "'JetBrains Mono', monospace" },
  heroName: {
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: "clamp(36px, 6vw, 64px)",
    color: "#fff",
    lineHeight: 1.1,
    marginBottom: 16,
    textShadow: "0 0 40px rgba(0,245,196,0.2)",
  },
  typewriterRow: { display: "flex", alignItems: "center", gap: 4, marginBottom: 20, minHeight: 40 },
  typewriterText: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(18px, 3vw, 26px)",
    color: "#7c6fff",
    fontWeight: 700,
  },
  cursor: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 28,
    color: "#00f5c4",
    animation: "blink 0.8s step-end infinite",
  },
  heroBio: { fontSize: 16, color: "#999", lineHeight: 1.8, marginBottom: 28, maxWidth: 480 },
  heroBtns: { display: "flex", gap: 16, flexWrap: "wrap", marginBottom: 28 },
  btnPrimary: {
    background: "#00f5c4",
    color: "#0a0a0f",
    border: "none",
    borderRadius: 8,
    padding: "12px 28px",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "transform 0.15s",
  },
  btnSecondary: {
    background: "transparent",
    color: "#00f5c4",
    border: "1.5px solid #00f5c4",
    borderRadius: 8,
    padding: "12px 28px",
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    textDecoration: "none",
    fontFamily: "'DM Sans', sans-serif",
    display: "inline-block",
  },
  socialRow: { display: "flex", flexWrap: "wrap", gap: 16, alignItems: "center" },
  socialLink: { color: "#666", fontSize: 13, textDecoration: "none", transition: "color 0.2s" },
  heroArt: {
    flex: "0 0 auto",
    position: "relative",
    width: 280,
    height: 280,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarRing: {
    width: 200,
    height: 200,
    borderRadius: "50%",
    background: "conic-gradient(from 0deg, #00f5c4, #7c6fff, #ff6b9d, #00f5c4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    animation: "spin 8s linear infinite",
  },
  avatar: {
    width: 180,
    height: 180,
    borderRadius: "50%",
    background: "#0d0d18",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 52,
    color: "#00f5c4",
  },
  floatBadge1: {
    position: "absolute",
    top: 10,
    right: -20,
    background: "#1a1a2e",
    border: "1px solid #00f5c4",
    color: "#00f5c4",
    borderRadius: 20,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    animation: "float 3s ease-in-out infinite",
    whiteSpace: "nowrap",
  },
  floatBadge2: {
    position: "absolute",
    bottom: 10,
    left: -30,
    background: "#1a1a2e",
    border: "1px solid #7c6fff",
    color: "#7c6fff",
    borderRadius: 20,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    animation: "float 3.5s ease-in-out infinite 0.5s",
    whiteSpace: "nowrap",
  },
};

export const experienceStyles = {
  section: {
    padding: "80px 6%",
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(26px, 4vw, 40px)",
    fontWeight: 700,
    color: "#fff",
    marginBottom: 8,
  },
  sectionSub: {
    color: "#666",
    fontSize: 16,
    marginBottom: 48,
  },
  timeline: { display: "flex", flexDirection: "column", gap: 0, paddingLeft: 32 },
  timelineItem: { display: "flex", gap: 24, position: "relative", paddingBottom: 32 },
  timelineDot: {
    width: 14,
    height: 14,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 6,
    position: "relative",
    zIndex: 1,
    boxShadow: "0 0 8px currentColor",
  },
  timelineLine: {
    position: "absolute",
    left: 6,
    top: 20,
    bottom: 0,
    width: 2,
    background: "linear-gradient(to bottom, #00f5c430, transparent)",
  },
  timelineCard: {
    background: "#0d0d18",
    border: "1px solid #1a1a2e",
    borderRadius: 12,
    padding: "20px 24px",
    flex: 1,
  },
  expHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12, flexWrap: "wrap", gap: 8 },
  expTitle: { fontFamily: "'JetBrains Mono', monospace", fontSize: 16, fontWeight: 700, marginBottom: 4 },
  expCompany: { color: "#777", fontSize: 14 },
  expPeriod: {
    fontSize: 12,
    border: "1px solid",
    borderRadius: 20,
    padding: "4px 12px",
    fontFamily: "'JetBrains Mono', monospace",
    whiteSpace: "nowrap",
  },
  expList: { listStyle: "none", display: "flex", flexDirection: "column", gap: 8 },
  expPoint: { display: "flex", alignItems: "flex-start", gap: 10, fontSize: 14, color: "#aaa", lineHeight: 1.6 },
  expBullet: { width: 6, height: 6, borderRadius: "50%", flexShrink: 0, marginTop: 7 },
};

export const projectsStyles = {
  section: {
    padding: "80px 6%",
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(26px, 4vw, 40px)",
    fontWeight: 700,
    color: "#fff",
    marginBottom: 8,
  },
  sectionSub: {
    color: "#666",
    fontSize: 16,
    marginBottom: 48,
  },
  projectsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 24,
  },
  projectCard: {
    background: "#0d0d18",
    border: "1px solid #1a1a2e",
    borderRadius: 12,
    padding: "28px 24px",
    transition: "transform 0.2s, box-shadow 0.2s",
    cursor: "default",
  },
  projTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 10,
    lineHeight: 1.4,
  },
  projDesc: { color: "#888", fontSize: 14, lineHeight: 1.7, marginBottom: 16 },
  tagRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  tag: {
    fontSize: 12,
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 6,
    padding: "4px 10px",
    fontWeight: 600,
  },
};

export const skillsStyles = {
  section: {
    padding: "80px 6%",
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(26px, 4vw, 40px)",
    fontWeight: 700,
    color: "#fff",
    marginBottom: 8,
  },
  sectionSub: {
    color: "#666",
    fontSize: 16,
    marginBottom: 48,
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 20,
  },
  skillCard: {
    background: "#0d0d18",
    border: "1px solid #1a1a2e",
    borderRadius: 12,
    padding: "24px 20px",
  },
  skillCat: {
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 15,
    marginBottom: 16,
  },
  skillPills: { display: "flex", flexWrap: "wrap", gap: 8 },
  skillPill: {
    fontSize: 13,
    borderRadius: 20,
    padding: "5px 14px",
    fontWeight: 500,
  },
};

export const achievementsStyles = {
  section: {
    padding: "80px 6%",
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(26px, 4vw, 40px)",
    fontWeight: 700,
    color: "#fff",
    marginBottom: 8,
  },
  sectionSub: {
    color: "#666",
    fontSize: 16,
    marginBottom: 48,
  },
  achieveGrid: { display: "flex", flexDirection: "column", gap: 20 },
  achieveCard: {
    background: "#0d0d18",
    border: "1px solid #1a1a2e",
    borderRadius: 12,
    padding: "24px 28px",
    display: "flex",
    alignItems: "center",
    gap: 20,
  },
  achieveIcon: { fontSize: 36, flexShrink: 0 },
  achieveTitle: { fontSize: 17, fontWeight: 600, color: "#e0e0e0", marginBottom: 6 },
  achieveDesc: { color: "#777", fontSize: 14 },
};

export const contactStyles = {
  section: {
    padding: "80px 6%",
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionTitle: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "clamp(26px, 4vw, 40px)",
    fontWeight: 700,
    color: "#fff",
    marginBottom: 8,
  },
  sectionSub: {
    color: "#666",
    fontSize: 16,
    marginBottom: 48,
  },
  contactBox: {
    background: "#0d0d18",
    border: "1px solid #1a1a2e",
    borderRadius: 16,
    padding: "48px 40px",
    textAlign: "center",
    maxWidth: 560,
    margin: "0 auto",
  },
  contactText: { color: "#888", fontSize: 16, lineHeight: 1.8, marginBottom: 28 },
  contactBtn: {
    display: "inline-block",
    background: "#00f5c4",
    color: "#0a0a0f",
    borderRadius: 8,
    padding: "14px 36px",
    fontWeight: 700,
    fontSize: 16,
    textDecoration: "none",
    marginBottom: 24,
    fontFamily: "'DM Sans', sans-serif",
  },
  contactLinks: { display: "flex", justifyContent: "center", alignItems: "center", gap: 12 },
  contactLink: { color: "#7c6fff", fontSize: 15, textDecoration: "none" },
};
